# Generated by Django 3.2.5 on 2022-01-05 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^(?=[a-zA-Z0-9._]{8,20}$)(?!.*[_.]{2})[^_.].*[^_.]$')])),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.TextField()),
                ('emailActivation', models.BooleanField(default=False)),
                ('nameOf', models.CharField(max_length=100)),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
    ]
