# Generated by Django 3.2.5 on 2021-11-15 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_payment_subpurchase_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('celebID', models.AutoField(primary_key=True, serialize=False)),
                ('nameOf', models.CharField(max_length=150)),
                ('gender', models.BooleanField()),
                ('dateOfBirth', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('filmID', models.AutoField(primary_key=True, serialize=False)),
                ('saleStatus', models.BooleanField(default=False)),
                ('salePercentage', models.PositiveIntegerField(default=0)),
                ('saleExpiration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreID', models.AutoField(primary_key=True, serialize=False)),
                ('nameOf', models.CharField(max_length=150)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('releaseDate', models.DateTimeField(null=True)),
                ('details', models.TextField()),
                ('saleStatus', models.BooleanField(default=False)),
                ('salePercentage', models.PositiveIntegerField(default=0)),
                ('saleExpiration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('showID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('seasons', models.IntegerField(default=1)),
                ('duration', models.PositiveIntegerField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('releaseDate', models.DateTimeField(null=True)),
                ('showStatus', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('details', models.TextField()),
                ('saleStatus', models.BooleanField(default=False)),
                ('salePercentage', models.PositiveIntegerField(default=0)),
                ('saleExpiration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='salePercentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='saleStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField()),
                ('qualityHeight', models.PositiveIntegerField()),
                ('qualityWidth', models.PositiveIntegerField()),
                ('sizeOf', models.PositiveIntegerField()),
                ('episode', models.PositiveIntegerField()),
                ('season', models.PositiveIntegerField()),
                ('encoder', models.CharField(max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('dateOf', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.film')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.user')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.movie'),
        ),
        migrations.AddField(
            model_name='film',
            name='tvshow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.tvshow'),
        ),
    ]
