# Generated by Django 3.2.5 on 2021-11-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20211115_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.celebrity')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.genre')),
            ],
        ),
        migrations.CreateModel(
            name='FilmDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.celebrity')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.celebrity')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.film')),
            ],
        ),
    ]
