# Generated by Django 3.2.5 on 2022-01-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='filmActor',
            field=models.ManyToManyField(related_name='film_actor', to='Core.Celebrity'),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmDirector',
            field=models.ManyToManyField(related_name='film_director', to='Core.Celebrity'),
        ),
    ]
