# Generated by Django 3.2.5 on 2022-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='encoder',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='episode',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
