# Generated by Django 3.2.5 on 2022-01-07 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^(?=[a-z0-9._]{5,20}$)(?!.*[_.]{2})[^_.].*[^_.]$')]),
        ),
    ]
