# Generated by Django 3.2.5 on 2022-01-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20220122_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='saleExpiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 12, 33, 1, 207893)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='saleExpiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 12, 33, 1, 211891)),
        ),
    ]
