# Generated by Django 3.2.5 on 2022-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20220127_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='saleExpiration',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='saleExpiration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
