# Generated by Django 3.2.5 on 2022-01-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20220127_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='saleExpiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='saleExpiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
