# Generated by Django 3.2.5 on 2022-01-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_genre_nameof'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='nameOf',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='nameOf',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
