# Generated by Django 3.2.5 on 2022-01-08 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20220108_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='filmID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userID',
        ),
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.film'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
