# Generated by Django 3.2.5 on 2022-01-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20220127_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(to='Core.Film'),
        ),
    ]
