# Generated by Django 3.2.5 on 2022-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20220108_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='film',
        ),
        migrations.AddField(
            model_name='video',
            name='filmID',
            field=models.IntegerField(null=True),
        ),
    ]
